//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int id { get; set; }
        public Nullable<int> format { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public Nullable<int> version { get; set; }
        public string preface { get; set; }
        public Nullable<int> quantityLeft { get; set; }
        public Nullable<int> warehouse { get; set; }
        public Nullable<System.DateTime> nextStockDate { get; set; }
        public Nullable<int> isbn { get; set; }
        public Nullable<bool> validIsbn { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> publisher_id { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual publishers publishers { get; set; }
    }
}
